### PR TITLE
StorageService: Normalize endpoint inetaddress strings to java form

### LINKED ISSUE #228: Endpoint strings in StorageService does not follow Java formatting for IPv6 nodes
This causes nodetool to break when mixing API:s returning actual IP addresses with info mapped by string.
Example is `nodetool status`.

Refs https://github.com/scylladb/scylladb/issues/16039

While this is really broken nodetool code, the problem is probably easier to fix here, in Scylla-JMX, as a stopgap until we can fully replace nodetool.

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #228

Endpoint strings in StorageService does not follow Java formatting for IPv6 nodes. This causes nodetool to break when mixing API:s returning actual IP addresses with info mapped by string. Example is nodetool status.

Refs scylladb/scylladb#16039

While this is really broken nodetool code, the problem is probably easier to fix here, in Scylla-JMX, as a stopgap until we can fully replace nodetool.

### CODE REVIEW

**Comment by avikivity** [comment]
@denesb please check native nodetool compatibility too

**Comment by denesb** [comment]
> @denesb please check native nodetool compatibility too

`nodetool status` is not implemented yet.

**Comment by avikivity** [comment]
ok, but please review this, since you're now our nodetool expert

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
Submodule update PR: https://github.com/scylladb/scylladb/pull/16146

**Pull request closed without merging**
