### PR TITLE
SCYLLA-VERSION-GEN: rm unnecessary Bashism

### PR DESCRIPTION
**Pull request by nodakai**
Make Debian's dash happy

### CODE REVIEW

**Review by nyh — APPROVED** [review]
Looks good.
Pending signature on CLA.

**Review by syuu1228 — APPROVED** [review]
LGTM

**Comment by yaronkaikov** [comment]
@nyh This PR is approved for 2 years. I assume we can close this?

**Comment by nyh** [comment]
My statement that this patch needs a signature on the CLA is still relevant - I still can't find a signed CLA for @nodakai, nor did he say that he did sign it and I need to look harder.

**Comment by nodakai** [comment]
Feel free to take inspiration from this PR of mine to make an independent commit

**Pull request closed without merging**
