### PR TITLE
Backport two dependency updates to branch-4.3

### PR DESCRIPTION
**Pull request by avelanarius**
Backport a commit updating snakeyaml dependency.

Update Jackson dependency to a newer version, without any known security vulnerabilities.

### CODE REVIEW

**Comment by avelanarius** [comment]
This PR cleanly applies also to the `branch-4.4`.

**Comment by avikivity** [comment]
branch 4.3 is long dead

**Comment by avikivity** [comment]
Active branches: 4.5, 4.6, 5.0.

**Comment by denesb** [comment]
@avelanarius why did you target 4.3 and 4.4? Are more recent branches not affected? If they are, we can backport to the active branches as described by @avikivity.

**Comment by avelanarius** [comment]
@denesb This fix of this PR is already in master. If I understand patch flow maintainer documentation correctly (I misunderstood it before), a maintainer should cherry pick fe351e84910017e0bd1f88c750bcd768081b5723 and 6b677f98c109ee298619a486a9dd374623e3a71a onto older branches.

**Comment by avikivity** [comment]
@avelanarius sorry to pile on more paperwork, but to backport something, we need an issue. So please create issues in scylla.git and immediately close them referencing the commits that fix the problem.

**Pull request closed without merging**
